# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.provider "virtualbox" do |v|
      v.memory = "2048"
 
    end
	puppetmaster.vm.hostname = "puppet"
	 puppetmaster.vm.provision "shell", inline: "wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb"
	 puppetmaster.vm.provision "shell", inline: "dpkg -i puppetlabs-release-pc1-trusty.deb"
   puppetmaster.vm.provision "shell", inline: "apt-get update"
   puppetmaster.vm.provision "shell", inline: "sudo apt-get install puppet-agent -y"
   puppetmaster.vm.provision "shell", inline: "/opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true"

    puppetmaster.vm.provision "puppet" do |puppet|
     #puppet.options = "--verbose --debug"
      puppet.environment_path = "environments"
      puppet.environment = "production"
      puppet.manifests_path = "environments/production/manifests"
      puppet.module_path   = "environments/production/modules"
      puppet.manifest_file = "site.pp"

    end
  end
 
end
